name: Automate Issue Assignment

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/rojinatefimehr/git_ci_test/issues/${{ github.event.issue.number }}/assignees
          assignees: rojinatefimehr
          token: ${{ secrets.GITHUB_TOKEN }}
