name: Assign and Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Explicitly grants write permission to manage issues

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-assign@v2
        with:
          route: POST /repos/rojinatefimehr/git_ci_test/issues/${{ github.event.issue.number }}/assignees
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: rojinatefimehr  # Replace with your GitHub username

      - name: Label Issue as "To Do"
        uses: rojinatefimehr/git_ci_test/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "To Do"
