name: Label New Issues as "To Do"

on:
  issues:
    types: [opened]

permissions:
  issues: write  

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Label new issue as "To Do"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "To Do"
name: Automate Issue Assignment and Labeling

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Grants write permission to manage issues

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
     
      - name: Assign issue to rojinatefimehr
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/rojinatefimehr/git_ci_test/issues/${{ github.event.issue.number }}/assignees
          assignees: rojinatefimehr
          token: ${{ secrets.GITHUB_TOKEN }}

   
      - name: Label new issue as "To Do"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "To Do"
