name: Assign and Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Grants write permission to manage issues

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Assign the issue
      - name: Assign Issue to rojinatefimehr
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/rojinatefimehr/git_ci_test/issues/${{ github.event.issue.number }}/assignees
          assignees: rojinatefimehr
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Label the issue as "To Do"
      - name: Label Issue as "To Do"
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/rojinatefimehr/git_ci_test/issues/${{ github.event.issue.number }}/labels
          labels: '["To Do"]'  # Label name must be in JSON array format
          token: ${{ secrets.GITHUB_TOKEN }}
